# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node runtime as a parent image
FROM node:16-alpine AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages
RUN npm install

# Build the project
RUN npm run build

# Use a smaller Node.js runtime for production
FROM node:16-alpine AS release

# Set the working directory to /app
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --production

# Set environment variables required by the MCP server
ENV TRELLO_API_KEY=your-api-key
ENV TRELLO_TOKEN=your-token
ENV TRELLO_BOARD_ID=your-board-id

# Run the MCP server
CMD ["node", "build/index.js"]